openapi: 3.0.3
info:
  title: Prices API
  version: 1.0.0
  description: API para consultar precios

paths:
  /prices/getPrice:
    get:
      summary: Obtener precio aplicable
      operationId: getPrice
      parameters:
        - name: applicationDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: productId
          in: query
          required: true
          schema:
            type: integer
        - name: brandId
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Precio encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Price'
        '404':
          description: No se encontró precio aplicable

components:
  schemas:
    Price:
      type: object
      properties:
        productId:
          type: integer
        brandId:
          type: integer
        priceList:
          type: integer
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        price:
          type: number
          format: float
        curr:
          type: string
          maxLength: 5
