openapi: 3.0.1
info:
  title: Prices API
  version: 1.0.0
  description: API para consultar el precio aplicable de un producto según fecha, producto y marca.

servers:
  - url: http://localhost:8080

paths:
  /prices/getPrice:
    get:
      summary: Obtener precio aplicable
      operationId: getPrice
      description: Retorna el precio aplicable de un producto para una fecha, producto y marca específicos.
      parameters:
        - name: queryDate
          in: query
          required: true
          description: Fecha y hora para la que se desea conocer el precio.
          schema:
            type: string
            format: date-time
        - name: productId
          in: query
          required: true
          description: Identificador del producto.
          schema:
            type: integer
        - name: brandId
          in: query
          required: true
          description: Identificador de la marca.
          schema:
            type: integer
      responses:
        '200':
          description: Precio encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Price'
              examples:
                Ejemplo:
                  value:
                    productId: 35455
                    brandId: 1
                    priceList: 1
                    startDate: "2020-06-14T15:00:00Z"
                    endDate: "2020-06-14T18:30:00Z"
                    price: 25.45
                    curr: "EUR"
        '400':
          description: Petición inválida. Faltan parámetros o están en formato incorrecto.
        '404':
          description: No se encontró un precio aplicable para los criterios enviados.
        '500':
          description: Error interno del servidor.

components:
  schemas:
    Price:
      type: object
      required:
        - productId
        - brandId
        - priceList
        - startDate
        - endDate
        - price
        - curr
      properties:
        productId:
          type: integer
          description: Identificador del producto.
        brandId:
          type: integer
          description: Identificador de la marca.
        priceList:
          type: integer
          description: Identificador de la tarifa de precio aplicada.
        startDate:
          type: string
          format: date-time
          description: Fecha y hora de inicio de la tarifa.
        endDate:
          type: string
          format: date-time
          description: Fecha y hora de fin de la tarifa.
        price:
          type: number
          format: float
          description: Precio aplicado.
        curr:
          type: string
          maxLength: 5
          description: Moneda en la que se expresa el precio (por ejemplo, "EUR", "USD").
